-- AlterTable
ALTER TABLE "AC" ALTER COLUMN "resetPasswordExpire" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "ADM" ALTER COLUMN "resetPasswordExpire" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "AM" ALTER COLUMN "resetPasswordExpire" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Decideur" ALTER COLUMN "resetPasswordExpire" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "SADM" ALTER COLUMN "resetPasswordExpire" SET DEFAULT CURRENT_TIMESTAMP;
