-- AlterTable
ALTER TABLE "AC" ALTER COLUMN "numTel" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "ADM" ALTER COLUMN "numTel" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "AM" ALTER COLUMN "numTel" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Client" ALTER COLUMN "numTel" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Consommateur" ALTER COLUMN "numTel" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Decideur" ALTER COLUMN "numTel" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "SADM" ALTER COLUMN "numTel" SET DATA TYPE TEXT;
